### PR TITLE
When auto-detecting, show also extracted metadata in result table

### LINKED ISSUE #301: Show on results the extracted metadata
Once #299 is merged, the web UI of Specberus will need to invoke `extractMetadata()` first, and display the information returned as `info()` messages on the results table.

### PR DESCRIPTION
**Pull request by tripu**
Looks like this:

exp

(If it's too intrusive, we can limit its height, like this:

coll

Although I prefer not to: scrollbars within scrollbars are annoying and not a good practice.)

Fixes #301.

**Merge before #503** (this goes on top of those changes).

### CODE REVIEW

**Comment by deniak** [comment]
Can't we just link to `/api/metadata`? This is not something useful most people using pubrules.
I think it's better to display only the important results on the UI. I'm pretty sure people only care about the errors and ignore the "advice".

**Comment by tripu** [comment]
Too much info that will be ignored? Mmmh, maybe.

What if we add just a line next to (or below) the one that says *&ldquo;n rules were checked. Hover over the rows below for options&rdquo;*, saying something like *&ldquo;see the metadata that was extracted form this document&rdquo;* with a link to `api/metadata` for the document?

**Comment by deniak** [comment]
:+1:

**Comment by tripu** [comment]
OK, I'll modify the PR.
(No need to hold #503 now).

**Comment by tripu** [comment]
Ready again, @deniak.
Hope this is what we both had in mind!

**Comment by deniak** [comment]
@tripu Perfect!

**Pull request merged**
