### PR TITLE
Quickfix #178: filter out URLs from paragraphs when checking for well-formed dates

### PR DESCRIPTION
**Pull request by astorije**
This doesn't fix everything, in particular it doesn't solve[@darobin's last comment on the subject](https://github.com/w3c/specberus/issues/178#issuecomment-91503953), but this provides a quick fix for #178 until something better shows up, featuring [this weird trick that will make your URLs disappear](http://stackoverflow.com/questions/23571013/how-to-remove-url-from-a-string-completely-in-javascript).

### CODE REVIEW

**Comment by mikewest** [comment]
So, any chance something like this "quickfix" could be merged and deployed? :)

**Comment by astorije** [comment]
I will let @tripu and/or @darobin assign themselves to this PR and review it.

**Comment by astorije** [comment]
@tripu do I understand you PR'ing into this branch as I can merge it into `master` myself?

**Comment by tripu** [comment]
Most definitely, @astorije. Sorry, I should have made that explicit.

**Pull request merged**
