### PR TITLE
Check new tag <meta name="viewport">

### PR DESCRIPTION
**Pull request by tripu**
cf. #267.

### CODE REVIEW

**Comment by deniak** [comment]
LGTM but I wonder if instead of looking for a specific value of the `content` attribute, we shouldn't [parse it](https://drafts.csswg.org/css-device-adapt/#parsing-algorithm) and check each property.
Currently, the following attributes are failing:
- `content='width=device-width,initial-scale=1,shrink-to-fit=no'`
- `content='initial-scale=1, width=device-width, shrink-to-fit=no'`

**Comment by tripu** [comment]
OK, @deniak. I think this check is no worse than those other checks we have (case-sensitive, verbatim text, even blanks are fixed).

But I'll do some simple parsing of the properties, as you said!

**Comment by dontcallmedom** [comment]
in case this helps, I have a [library that parses meta viewport content attributes](https://github.com/dontcallmedom/metaviewport-parser).

**Comment by tripu** [comment]
@deniak: I used @dontcallmedom's package (cheers!) for proper parsing; I think the check is better now.

OK to merge before 1 March?

**Comment by deniak** [comment]
@tripu it's ready to be merged. Nice work.

**Pull request merged**
