### PR TITLE
[On hold] Drop rule about link to translations

### LINKED ISSUE #552: [Under assessment] Delete rule requiring link to translations page?
eg, [`w3.org/pubrules/doc/rules/?profile=REC#translation`](https://www.w3.org/pubrules/doc/rules/?profile=REC#translation)

### LINKED ISSUE #730: Bug in rules: [translation link]
**Warning:**
"The recommended link is not used (http[s]://[www.]w3.org/2003/03/Translations/byTechnology?technology=[shortname])"

But it is:

&lt;p>See also &lt;a href="http://www.w3.org/2003/03/Translations/byTechnology?technology=WOFF2"> &lt;strong>translations&lt;/strong>&lt;/a>.&lt;/p>

Found [while checking `https://www.w3.org/TR/2018/REC-WOFF2-20180220/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2018%2FREC-WOFF2-20180220%2F&profile=REC&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

### PR DESCRIPTION
**Pull request by tripu**
Closes #552, closes #730.

### CODE REVIEW

**Comment by plehegar** [comment]
@koalie , ok to remove the link to translations from REC requirements?

**Comment by deniak** [comment]
@plehegar we discussed that PR on IRC and it's not clear yet what we'll do regarding the translations. We *might* still require a link to translations but hosted somewhere else.
Decision is to leave that PR open until we agree on a solution.

**Comment by plehegar** [comment]
Unassigned until Comm knows what to do with translations

**Comment by tripu** [comment]
@koalie, ping?

**Comment by koalie** [comment]
Hi @tripu 
Sorry, I didn't see that ping from July :(
We have stopped maintaining the translation DB many months ago and no suitable replacement solution has been brought forward. This is in the hands of Angel from Beihang. @lianqi 
I would advise we *remove* the link to the translations DB from the spec generator(s).
I was again reminded of this reading Anne van Kesteren's [tweet](https://twitter.com/annevk/status/960576373009117184) today that a translation link is still part of a given spec.

**Comment by tripu** [comment]
@koalie, no worries!

@deniak, I just rebased this branch (and removed all traces of &ldquo;translations&rdquo; from the new profile REC-SUPERSEDED, too). Can you quickly review again, please?

@lianqi, awaiting instructions&hellip; :robot:

**Comment by svgeesus** [comment]
So, could this be merged? Ran into the translation link issue again a couple of times recently and @plehegar said to drop the translations link.

**Comment by deniak** [comment]
AFAIK, we haven't agreed yet what will happen to the translations for specs...

**Comment by tripu** [comment]
Yes, I'm not sure we were completely ready to merge this yet&hellip;
@lianqi isn't part of the team any more. @koalie, what shall we do with translations?

**Comment by koalie** [comment]
> On 19 Jun 2018, at 12:16 , tripu <notifications@github.com> wrote:
> 
> Yes, I'm not sure we were completely ready to merge this yet…
> @lianqi isn't part of the team any more. @koalie, what shall we do with translations?

Ditto, tripu.
But, given the uncertainties regarding how we will tackle translations, this is fine that it was (prematurely) merged. I think when we know more regarding the former, we can do something about the latter.

Coralie

> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Coralie Mercier  -  W3C Marketing & Communications -  https://www.w3.org
mailto:coralie@w3.org +337 810 795 22 https://www.w3.org/People/CMercier/

**Comment by plehegar** [comment]
This has been lingering for too late imho. Requiring a link to a database that is no longer maintained doesn't make sense to me. It's unfortunate that we don't have an alternative solution but we need to drop the link.

**Comment by deniak** [comment]
Good enough for me

**Pull request merged**
