### PR TITLE
Groupnote pp

### PR DESCRIPTION
**Pull request by plehegar**
Based on a discussion with @wseltzer .

New wording for WG Note should only be:
[[
This document was produced by a group operating under the W3C Patent Policy.
]]

(and nothing else following)

### CODE REVIEW

**Comment by deniak** [comment]
It's actually breaking the way we extract the WG delivering the spec. We rely on the patent disclosures link that contains the WG id and the change removes that link. Can we request a `data-deliverer` attribute somewhere in the SotD so we can identify the WG?

**Comment by plehegar** [comment]
sure, we can certainly do so.

**Comment by plehegar** [comment]
@deniak ok, I think it's ready now for your final review.

**Comment by plehegar** [comment]
thinking more here: should we add a data-deliverer rule as well?
 Otherwise I'm not sure how folks are supposed to know about this...

**Comment by deniak** [comment]
@plehegar the pull request should be ready now. I've added a new rule for the profile `WG-NOTE` to require a `data-deliverer` attribute in the SotD.
@tripu if you have time, can you please review that PR as well? Thanks!

**Comment by deniak** [comment]
@tripu indeed. Comments addressed.

**Comment by deniak** [comment]
@tripu I should have thought about it earlier. Done now.

**Comment by tripu** [comment]
(Waiting to merge until we coordinate changes with Respec &amp; Bikeshed maintainers&hellip;)

**Comment by deniak** [comment]
Issues to be monitored:
- [ ] [Bikeshed](https://github.com/tabatkins/bikeshed/issues/1153)
- [ ] [ReSpec](https://github.com/w3c/respec/issues/1443)

**Comment by deniak** [comment]
Respec has been updated. Once bikeshed is updated (/cc @tabatkins), we will be able to deploy that PR in production.

**Comment by deniak** [comment]
https://github.com/tabatkins/bikeshed/pull/1157 is now merged. AFAIK, we are ready to merge and deploy that PR.

**Pull request merged**
