### PR TITLE
fix SotD detection after the 2016 TR design

### LINKED ISSUE #290: The new TR design breaks the SotD detection
[getSotDSection](https://github.com/w3c/specberus/blob/master/lib/validator.js#L191) currently relies on the `<h2>` following the SotD:
```
<h2>Status of this Document</h2>
...
<h2>Table of Contents</h2>
```

With the upcoming TR design breaks, it's no longer possible to rely on it as the table of contents is inside a navigation element:
```
<h2>Status of this Document</h2>
...
<nav>
    <h2>Table of Contents</h2>
    ...
</nav>
```

### PR DESCRIPTION
**Pull request by deniak**
Fix #290 
**Do not merge before Feb 29**

### CODE REVIEW

**Comment by plehegar** [comment]
:+1:

**Comment by tripu** [comment]
This one needs rebasing now.

**Comment by deniak** [comment]
@tripu, it's ready now

**Comment by tripu** [comment]
Great. I'll merge after tr-design deployment this week.

**Comment by deniak** [comment]
@tripu this is part of the new 2016 TR style

**Pull request merged**
