### PR TITLE
css-ui-4 uses the caret-shape property

### PR DESCRIPTION
**Pull request by xfq**
[[
Error: CSS: caret-shape: Property caret-shape doesn't exist.
]]
when checking the css-ui-4 document: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdrafts.csswg.org%2Fcss-ui-4%2F

/cc @plehegar @deniak

### CODE REVIEW

**Comment by deniak** [comment]
@xfq I think you are mixing the markup and the CSS validator. Your PR adds an exception for the CSS validator `validation.css` but the link you mention points to the markup validator.
Looking at the [previous document](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FWD-css-ui-4-20200102%2F&profile=WD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004), the exception should be on `validation.html` and the message `CSS: “caret-shape”: Property “caret-shape” doesn't exist.` (see [json output](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdrafts.csswg.org%2Fcss-ui-4%2F&out=json))

**Comment by xfq** [comment]
@deniak Ah, right. I just updated the PR.

**Comment by deniak** [comment]
Looks good to me. I'll add @plehegar as reviewer

**Comment by plehegar** [comment]
@deniak Not sure why the Travis CI is failing. I'll let you merge this.

**Pull request merged**
