### PR TITLE
README.md: move the badges after the title

### PR DESCRIPTION
**Pull request by deniak**
The description on [npmjs](https://www.npmjs.com/~w3c) is messed up because of the badges in `README.md`

### CODE REVIEW

**Comment by tripu** [comment]
Well spotted, @deniak.

**Comment by astorije** [comment]
Good catch indeed, but I'm afraid I have to :-1: this PR as I don't think it's the way to go: I would prefer to keep the badges on the first line (for convention), and we don't have control on where the description used by npm stops.

Instead, I'd prefer to set the `description` tag of `package.json`. I did that in #195. I assign both PRs to @tripu to be the referee and decide which PR you want to merge and which one to discard :-)

**Comment by tripu** [comment]
I think the solution suggested in #195 is better.

**Comment by deniak** [comment]
Indeed, it's better to not rely on the `README.md`. Thanks @astorije

**Pull request closed without merging**
