### PR TITLE
Betterify the hyperlink to "reset" the app (follow-up #181)

### PR DESCRIPTION
**Pull request by tripu**
The hyperlink added in PR #181 is broken *unless the app happens to be deployed at `[host]/pubrules/`*. Fixing that.

### CODE REVIEW

**Comment by astorije** [comment]
@tripu, sorry #181 got merged without your approval. I was surprised to see @darobin merging rogue :D

Regarding this PR, as much as I hate doing so, I think I need to :-1: here. Although I am not a JS-hater (that would be pointless considering the rest of the page is full JS), I don't feel comfortable having an inline JS string for a simple link.

I think it should stay that way, nevermind if it's broken if you install it some place else. What does @darobin think about this?

**Comment by darobin** [comment]
Merging rogue? I wasn't aware we had rules, I probably didn't get that memo :)

**Comment by astorije** [comment]
Anarchist!

**Comment by astorije** [comment]
@darobin what do you think of this PR?

**Comment by darobin** [comment]
Can we back out to the goal here? It looks like the intent is to effectively reset the parameters. Wouldn't it be better to add a reset button to the form?

Also: who cares if the link only works when deployed there? I would suggest that anyone developing locally should also use `/pubrules/` locally, otherwise you might make a mistake with an include or something.

**Comment by astorije** [comment]
> Can we back out to the goal here? It looks like the intent is to effectively reset the parameters. Wouldn't it be better to add a reset button to the form?

Nah, not really. I agree a reset button is needed, but that's not the goal here IMO.
The goal is just to provide a link to the "entry page" behind the navbar logo, which I see as a standard practice on pretty much all the websites today. I surprise myself being frustrated when such link doesn't exist, because that became a mechanism for me to go back to the index page.

> Also: who cares if the link only works when deployed there? I would suggest that anyone developing locally should also use `/pubrules/` locally, otherwise you might make a mistake with an include or something.

Right, not really a problem if it only works when deployed.
I also :+1: your suggestion to use `/pubrules/` locally. Is there something that needs to be changed on `app.js` (or else) to set this as a base?

**Comment by tripu** [comment]
OK. I'm outnumbered here; closing this one :¬)

Further talk about forcing deployment at `/pubrules/`, or adding a reset button, in separate issues/PRs.

**Pull request closed without merging**
